# Generated by Django 4.2.8 on 2023-12-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('isBookmarked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('isLiked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('avatar', models.URLField()),
                ('bgImage', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('count', models.IntegerField(default=0)),
                ('desc', models.TextField(default='')),
                ('jobName', models.CharField(default='', max_length=255)),
                ('href', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('href', models.URLField()),
                ('count', models.IntegerField(default=0, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=2000)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy', models.CharField(choices=[('category', 'Category'), ('tag', 'Tag')], default='category', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('href', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('featuredImage', models.URLField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('commentCount', models.IntegerField()),
                ('viewdCount', models.IntegerField()),
                ('readingTime', models.IntegerField()),
                ('postType', models.CharField(choices=[('standard', 'Standard'), ('video', 'Video'), ('gallery', 'Gallery'), ('audio', 'Audio')], max_length=50)),
                ('videoUrl', models.URLField(blank=True, null=True)),
                ('audioUrl', models.URLField(blank=True, null=True)),
                ('galleryImgs', models.JSONField(blank=True, null=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.postauthor')),
                ('bookmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.bookmark')),
                ('categoriesId', models.ManyToManyField(to='news.taxonomy')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.like')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
